[credentials]
usernames = { "omartg" = {name = "Product Owner", password = "$2b$12$R/NG1aOC4BfWUNeYs.eKfOIDN.KRMCjMh5X2hPeXepb4rilI/Ni5u"} }
[cookie]
name = "monitoreo_auth"
key = "una_clave_larga_y_aleatoria_para_encriptar"
expiry_days = 30
