[credentials]
usernames = { "omartg" = {name = "Product Owner", password = "$2b$12$MoCRQwnv8OnYW0ndoxC8gO0pjWrsr5KPMd/mqYfUSiHYq0A54hUsC"} }

[cookie]
name = "monitoreo_auth"
key = "una_clave_larga_y_aleatoria_para_encriptar"
expiry_days = 30